version: '3'
services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "kanban"
      POSTGRES_NAME: "kanban"
      POSTGRES_USER: "kanban"
      POSTGRES_HOST_AUTH_METHOD: trust
  django:
    build: ./backend/backend
    image: backend 
    ports:
      - "8080:8080"
    # command: python3 ./manage.py runserver 0.0.0.0:8030
    # volumes: 
    #   - .:/app
    depends_on: 
      - db
  node:
    build: ./frontend
    image: frontend
    ports:
      - "8000:8000" 
    # command: npm run dev
    # volumes:
    #   - .:/app
    depends_on:
      - db
  # nginx:
  #   restart: always
  #   build: ./nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - web-static:/www/static
  #   links:
  #     - web:web