# Generated by Django 3.0.5 on 2020-04-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='column',
        ),
        migrations.AddField(
            model_name='column',
            name='items',
            field=models.ManyToManyField(to='kanban.Item'),
        ),
    ]
