# Generated by Django 3.0.5 on 2020-04-10 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_auto_20200410_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='column',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kanban.Column'),
            preserve_default=False,
        ),
    ]
