# Generated by Django 3.0.5 on 2020-04-10 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20200410_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kanban.Column'),
        ),
    ]
